---
title: "Rewrite lm() and anova()"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message = FALSE) 
```

# Task 1: 
Rewrite the `lm()` function that returns output similar to `summary(lm())$coef`

```{r}
# make some fake data
n=100
  b=c(4,-4,3)
  p=length(b)
  x1=rnorm(n)
  x2=runif(n)
  x3=rbinom(n,size=1,prob=.3)
  signal=20+cbind(x1,x2,x3)%*%b
  error=rnorm(n=n,sd=sd(signal))
  y=signal+error
data <- cbind(x1,x2,y, x3)
colnames(data) <- c("y", "x1", "x2", "x3")
data <- as.data.frame(data)
```


```{r define-mylm}
mylm <- function (formula, data, rounding = 7) {
  
  formula <- gsub("[[:space:]]", "", deparse(formula))
  vars <- strsplit(formula, "[[:punct:]]")[[1]]
     
  y <- data[,vars[1]]
  A <- data.matrix(cbind(1, data[,vars[-1]]))
  
  betahat <- solve(crossprod(A)) %*% t(A) %*% y
  betahat <- as.vector(betahat)
  RSS <- t(y - (A %*% betahat)) %*% (y - (A %*% betahat))
  MSE <-  as.numeric(RSS) / (nrow(A) - length(vars))
  var_betaHat <- MSE * solve(crossprod(A))

  se_vec <- sqrt(diag(var_betaHat))
   t_vec <- betahat / se_vec
   p_val <- pt(abs(t_vec), df = nrow(data) - ncol(data) - 1, lower.tail = F) * 2

  output <- data.frame(round(betahat, rounding), round(se_vec, rounding), 
                          round(t_vec, rounding), round(p_val, rounding))

  colnames(output) <- c("Estimate", "Std. Error", "t value", "Pr(>|t|)")
  rownames(output) <- c("(Intercept)", vars[-1])
  output <- as.matrix(output)

  return(output)
}
```

```{r testing-mylm}
mylm(y ~ x1 + x2 + x3, data = data)
summary(lm(y ~ x1 + x2 + x3, data = data))$coef
```

# Task 2: 
Rewrite the `anova()` function that returns output similar to `print(anova())`

```{r}
myanova <- function (fit0, fit1, rounding = 3) {

RSS0 <- sum(residuals(fit0)^2)
RSS1 <- sum(residuals(fit1)^2)
MSS  <- RSS0 - RSS1
n <- length(residuals(fit0))

df0 <- length(coef(fit1)) - length(coef(fit0))
df1 <- n - length(coef(fit1))

Fstat <- (MSS / df0) / (RSS1 / df1)
pval  <- pf(Fstat, df1 = df0, df2 = df1, lower.tail = FALSE)
res.df <- c(df1, n - df0 -1)
one <- c(round(c(n - df0 - 1, RSS0), rounding), rep("", 4))
two <- c(df1, RSS1, df0, RSS0 - RSS1, Fstat, pval)

model1 <- c(paste("model 1:", deparse(formula(fit0))))
model2 <- c(paste("model 2:", deparse(formula(fit1))))

output <- rbind(one, round(two, rounding), deparse.level = 0)
colnames(output) <- c("Res.Df", "RSS", "Df", "Sum of Sq", "F", "Pr(>F)")
 cat("Analysis of Variance Table\n")
 cat(paste("\nmodel 1:", deparse(formula(fit0))))
 cat(paste("\nmodel 2:", deparse(formula(fit1))))
 output <- as.data.frame(output)
 return(output)
}
```

```{r}
DATA <- read.csv("https://raw.githubusercontent.com/despresj/portfolio/main/data/su-gout.csv")
```

```{r}
fit0 <- lm(su ~ race + age, DATA)
fit1 <- lm(su ~ race + age + race * sex, DATA)

myanova(fit0, fit1)
print(anova(fit0, fit1))
```